# Generated by Django 4.1.3 on 2022-11-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=datetime.datetime(2022, 11, 8, 12, 10, 58, 319113, tzinfo=datetime.timezone.utc), max_length=60, verbose_name='Подробное описание'),
            preserve_default=False,
        ),
    ]
